# Generated by Django 3.1.7 on 2021-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
