# Generated by Django 3.1.7 on 2021-04-03 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210403_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_info', to='order.addressinfo'),
        ),
    ]
