# Generated by Django 3.1.7 on 2021-04-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210403_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_info',
        ),
    ]
