# Generated by Django 3.1.7 on 2021-04-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_address_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-ordered_date',)},
        ),
    ]
