# Generated by Django 3.1.7 on 2021-04-03 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210403_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
    ]
