# Generated by Django 3.1.7 on 2021-04-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='actual_price',
        ),
    ]
