# Generated by Django 3.1.7 on 2021-04-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20210402_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='actual_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
