# Generated by Django 3.1.7 on 2021-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20210402_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='prod_imgs/'),
        ),
    ]
