# Generated by Django 3.1.7 on 2021-04-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20210402_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
    ]
